
[real_peaceful_mode-common-config]

	#You can determine whether each mission will be triggered or not.
	[real_peaceful_mode-common-config.missions]
		#ID of missions to disable. Disabled missions cannot be received or finished by players. If you disable the last mission of a monster's quest, this monster will never become passive. And if you disable mission A required by mission B, B can be triggered without finishing mission A.
		DISABLE_MISSIONS = []

	#You can determine whether each random event will happen to a hero player or not.
	[real_peaceful_mode-common-config.random-events]
		#Entity Type ID of monsters to disable. For example, if you add "minecraft:zombie" to this list, no random events will trigger after you complete zombies' quests.
		DISABLE_EVENTS = []
		#How many ticks (20 ticks = 1 second) will delay for a try to spawn a random event
		#Range: 1200 ~ 192000
		RANDOM_EVENT_CHECKER_INTERVAL = 20000
		#The possibility (in percentage) for spawning a random event during a try.
		#Range: 0 ~ 100
		RANDOM_EVENT_POSSIBILITY = 25
		#If last try failed to spawn a random event, how much will the possibility increase next time. If success, it will be back to RANDOM_EVENT_POSSIBILITY.
		#Range: 0 ~ 50
		RANDOM_EVENT_POSSIBILITY_ADDER = 5
		#The max possibility (in percentage) for spawning a random event. It will never be more than this value.
		#Range: 0 ~ 100
		RANDOM_EVENT_POSSIBILITY_MAX = 80

